### ISSUE TITLE
License for this codebase

### ISSUE THREAD

**Issue by siemvaessen** [IATI/js-validator-api#121]
Will there be a license distributed with this codebase?

**Comment by nosvalds** [comment]
Hello,

The license information is displayed in the footer (bottom-right) of the Validator website:

https://iativalidator.iatistandard.org/

<img width="354" alt="image" src="https://user-images.githubusercontent.com/60047271/133982881-9494ae07-4847-40bc-8090-db9ac80028c0.png">

We will look into adding this to the repositories for posterity.

**Comment by nosvalds** [comment]
https://github.com/IATI/js-validator-api/blob/develop/LICENSE.md
