### ISSUE TITLE
CORS policy blocking API requests

### ISSUE THREAD

**Issue by sylvanr** [IATI/js-validator-api#183]
Hi guys,

While setting up ad-hoc validation of a file, I've tried axios and fetch, on both localhost and on a server with https set up, but both result in the same issue: 
```
Access to XMLHttpRequest at 'https://api.iatistandard.org/validator/validate?group=true&details=false' from origin has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
The headers that are being passed are `Content-Type`, `Accept`, `Cache-Control` and `Ocp-Apim-Subscription-Key`. Basically copied from the [API docs](https://developer.iatistandard.org/api-details#api=iati-validator-v2&operation=post-pub-validate-post).

Using the same headers and data in Postman (and on the validator API docs 'try me' feature), does return the validation report as expected.

Is this an issue where a user would need additional parameters? Or is this something that could be changed server-side?

Cheers,
Sylvan

**Comment by alexlydiate** [comment]
Hello - what is your use-case here? CORS should only apply when requests are made from a browser; if you are trying to make the request from browser-side JavaScript that would be the expected behaviour.

**Comment by sylvanr** [comment]
Thanks for the quick answer @alexlydiate, 

the use-case was indeed to make a request directly from the browser-side. Have now changed this to fit the functionality of what has been built! So closing with comment.
